[package]
name = "mirage"
version = "0.1.0"
authors = ["eomain"]
description = "A library for describing vector graphics"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
